### ISSUE TITLE
When I switch to 2.1.0_beta, parse() method cannot be invoked

### ISSUE THREAD

**Issue by JeffRisberg** [FredrikOseberg/react-chatbot-kit#106]
Recently tried the 2.1.0_beta branch.

I get the message "i.parse" is not a function.  I appears that the API for the MessageParser component must have changed.

Do you have an example of using 2.1.0?  I also want to use the payload facility, which appears to only be in 2.1.0

Thanks.

**Comment by FredrikOseberg** [comment]
Hi. This tag `2.1.0-beta.1` should still work in a backwards compatible manner. I have been working on building support for writing the MessageParser and ActionProvider as react components so you can use hooks.

**Comment by JeffRisberg** [comment]
I agree that it should, and the code in the tag seems correct.  But I get:

react-dom.development.js:4091 Uncaught TypeError: i.parse is not a function
    at onSubmit (index.js:1:9562)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:25)
    at executeDispatch (react-dom.development.js:8243:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:7)
    at processDispatchQueue (react-dom.development.js:8288:5)
    at dispatchEventsForPlugins (react-dom.development.js:8299:3)
    at eval (react-dom.development.js:8508:12)

After switching to the 2.1.0_beta.1 branch.  I will keep trying.

**Comment by FredrikOseberg** [comment]
Do you have your code somewhere publicly available?

**Comment by JeffRisberg** [comment]
yes, it is located in https://github.com/JeffRisberg/chatbot01
this code is largely the tutorial you provided, building the Learning Chatbot with LearningOptions and LinkedList components.  Runs find 2.0.1, fails with 2.1.0-beta.1

**Comment by FredrikOseberg** [comment]
> yes, it is located in https://github.com/JeffRisberg/chatbot01 this code is largely the tutorial you provided, building the Learning Chatbot with LearningOptions and LinkedList components. Runs fine with 2.0.1, fails with 2.1.0-beta.1

Curious. It seems to run fine when I start the app on my end: https://www.loom.com/share/7aed66989f1245a98f89798985cd3d79?focus_title=1&muted=1&from_recorder=1

**Comment by JeffRisberg** [comment]
I watched the video you submitted.  In it, there was no call to messageParser.parse() that was succeeding.  The only responses were the initial message, and clicking on the JavaScript button, which runs the actionHandler directly.

If you type "javascript" rather than clicking the button you will get the following screen shot:
![2022-04-20_05-01-33](https://user-images.githubusercontent.com/493010/164226503-3d72a192-ff02-41af-aaa9-ea006ee3a921.jpg)

**Comment by FredrikOseberg** [comment]
> 

Might be that the beta version is not up to date with the latest changes. Can you try this one: `2.1.0-beta.2` ?

**Comment by FredrikOseberg** [comment]
> Thanks, that worked!
> 
> All message parsing and action handling functions are working as in 2.0.1. Now I will start working with the message payload facility. There isn't documentation, but I can see how you have added field(s) to the message data record, and how this is passed to the rendering of the widgets.
> 
> Much appreciated.

Awesome! Thanks for reminding me of this, the docs are undergoing some revamp due to the rewrite. I've been postponing it, but seeing as it's basically ready to go I need to get it out soon :)
